build_from:
  amd64: ghcr.io/hassio-addons/base/amd64:stable
  aarch64: ghcr.io/hassio-addons/base/aarch64:stable
  armv7: ghcr.io/hassio-addons/base/armv7:stable
args:
  BUILD_FROM: ghcr.io/hassio-addons/base/amd64:stable
